#!/bin/sh
#
#PBS -S /bin/sh
#PBS -V
#PBS -j oe
#PBS -N "MESS.DB_calculate___METHOD__"

module load python
module load openbabel
module load balloon
module load mopac

export BALLOON_FORCEFIELD=/opt/balloon_x86_64/MMFF94.mff

cd $PBS_O_WORKDIR

python -u mess select --part __PART__ --of __THREADS__ | python -u mess calculate -m __METHOD__ -p __PATH_ID__ &>>__PATH_TO_LOGS__/calculate___METHOD__.log
